[FIO internal] imx8mp_evk: set CONFIG_SYS_BOOTM_LEN for 64MB
This setting is missing from imx8mp which causes the following error
during fit-image load via bootm:
Error: inflate() returned -5
Image too large: increase CONFIG_SYS_BOOTM_LEN
Must RESET board to recover

Signed-off-by: Michael Scott <mike@foundries.io>