[FIO toup-squash] DM: crypto/fsl: fix bogus dereferencing
Fix bogus dereferencing causing the compiler error [1].

[1]
drivers/crypto/fsl/fsl_rsa.c:26:29: warning: dereferencing ‘void *’ pointer
   26 |  fdt64_t exp = fdt64_to_cpu(*prop->public_exponent);
      |                             ^~~~~~~~~~~~~~~~~~~~~~
...
include/linux/byteorder/little_endian.h:39:50: error: invalid use of void expression
   39 | #define __be64_to_cpu(x) __swab64((__force __u64)(__be64)(x))
      |                                                  ^
---------------------------------------------------------------------

Fixes: 6b0c6d7383 ("[FIO toup] DM: crypto/fsl: fix alignment issue in fsl_rsa driver")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>