[FIO internal-squash] cmd: fiovb: add include for boot_mode_is_closed
Add include sys_proto.h, where boot_mode_is_closed() is defined.

This fixes this compile time warning:
cmd/fiovb.c:23:7: warning: implicit declaration of function 'boot_mode_is_closed' [-Wimplicit-function-declaration]
23 |  if (!boot_mode_is_closed())
   |       ^~~~~~~~~~~~~~~~~~~

Fixes: 545d964536 ("[FIO extras] fiovb: return error on init if board not closed")
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
(cherry-picked from 26f9df8e614550ffacc5327384d95ff97045349f)
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>