[FIO internal] cmd: fiovb: add include for boot_mode_is_closed
Add include sys_proto.h, where boot_mode_is_closed() is defined.

This fixes this compile time warning:
cmd/fiovb.c:23:7: warning: implicit declaration of function 'boot_mode_is_closed' [-Wimplicit-function-declaration]
23 |  if (!boot_mode_is_closed())
   |       ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>