[FIO toup] board: st: stm32mp1: fix building w/o CONFIG_VIDEO
The module fdt_simplefb.c includes several functions. The function
fdt_simplefb_enable_and_mem_rsv() used in stm32mp1.c is available
only if CONFIG_VIDEO enabled. Fix building error [1] if
CONFIG_VIDEO disabled.

[1]
| arm-lmp-linux-gnueabi-ld.bfd: board/st/stm32mp1/stm32mp1.o: in function `ft_board_setup':
| board/st/stm32mp1/stm32mp1.c:936: undefined reference to `fdt_simplefb_enable_and_mem_rsv'

Fixes:   8ad37e6f16d ("board: stm32mp1: enable simple framebuffer node for splashscreen")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>