[FIO internal] imx8qm_mek: increase CONFIG_SYS_BOOTM_LEN
Increase CONFIG_SYS_BOOTM_LEN, which fixes this issue during
decompression of kernel:
Error: inflate() returned -5
Image too large: increase CONFIG_SYS_BOOTM_LEN
Must RESET board to recover

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
(cherry picked from commit 2b0632544b57af650b813f062d57633b5d372fd3)